name: React App CI TEST

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          version: 18.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Build Prod
        run: npm run build
# jobs:
#   react-app-workflow:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - uses: actions/setup-node@v4
#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20.x"
#       - run: npm i
#       - run: npm run build
