name: React App CI TEST

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  react-app-workflow:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    strategy:
      matrix:
        node-version: ['10.x', '12.x', '14.x', '18.x'] # Assuming you meant to include Node.js 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run:
          npm ci

          # - name: npm ci
      #   run: npm ci
      # - name: test
      #   run: npm test
      # - name: format
      #   run: npm run prettier
      # - name: lint
      #   run: npm run lint
      # - name: typescript
      #   run: npm run typescript
      # - name: build
      #   run: npm run build --if-present

      # //======
# jobs:
#   react-app-workflow:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     strategy:
#       matrix:
#         node-version: [16.x]
#     steps:
#       - uses: actions/setup-node@v2
#       - name: Setup Node ${{matrix.node-version}}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{matrix.node-version}}
#       - name: npm install
#         run: npm ci
#       - name: linting the code
#         run: npm lint
